### ISSUE TITLE
Création d'un dossier d'exemples

### ISSUE THREAD

**Issue by Bubobubobubobubo** [sova-org/Sova#21]
Créer un dossier d'exemples nommés pour tester plus rapidement certaines fonctionnalités. Exemple de structure dans le `Cargo.toml` : 

```toml

[[example]]
name = "minimal"
required-features = ["crossterm"]

[[example]]
name = "editor"
required-features = ["crossterm", "search"]

[[example]]
name = "split"
required-features = ["crossterm"]

[[example]]
name = "single_line"
required-features = ["crossterm"]
```

Puis pour faire tourner : `cargo run --example blabla`.
